export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";
export const CREATE_POST = "CREATE_POST";
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export const DELETE_POST = "DELETE_POST";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
